/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package IndianStatesCensus;

import java.io.*;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Collectors;

import com.opencsv.*;
import com.google.gson.*;
import csvutility.*;

public class CSVFileOperations<E> {
	
	
	public static boolean checkHeaderArrayFilePathAndDelimiter(String[] mapping, String path, char delimiter) throws CustomException {
		try {
			Reader reader = Files.newBufferedReader(Paths.get(path));
			CSVParser parser = new CSVParserBuilder().withIgnoreQuotations(true).withSeparator(',').build();
			CSVReader csvReader = new CSVReaderBuilder(reader).withCSVParser(parser).build();
			String[] header = csvReader.readNext();
			if (header == mapping && delimiter==',')
				return true;
			else if(header!=mapping && delimiter==',')
				throw new CustomException(CustomException.ExceptionType.INCORRECT_HEADER, "Header array is incorrect!");
			else if(header!=mapping && delimiter!=',') 	
				throw new CustomException(CustomException.ExceptionType.INCORRECT_DELIMITER,"Delimiter entered is not correct!");
		} catch (IOException e) {
			throw new CustomException(CustomException.ExceptionType.FILE_NOT_FOUND, "File Not Found!");
		}
		return false;
	}
	
	public int getCount(List<E> list) {
		return list.size();
	}
	
	public String sortStateData() throws CustomException
	{
		List<StatesCensusAnalyzer> statesData = StatesCensusAnalyzer.getCensusDataCount("./src/main/resources/IndianStateCensusData.csv");
		List<StatesCensusAnalyzer> sortedData = statesData.stream().sorted((p1,p2)->p1.getStateName().compareToIgnoreCase(p2.getStateName())).collect(Collectors.toList());
		String sortedStateCensus=new Gson().toJson(sortedData);
		return sortedStateCensus;
	}
}